[programs.localnet]
solana_twitter = "6Cknn14FunFsPTS9A3kRkWdMGrgwzYGzDMPnT1YGQ1Gt"

[programs.devnet]
solana_twitter = "6Cknn14FunFsPTS9A3kRkWdMGrgwzYGzDMPnT1YGQ1Gt"

[programs.mainnet]
solana_twitter = "6Cknn14FunFsPTS9A3kRkWdMGrgwzYGzDMPnT1YGQ1Gt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/anchor/idl && cp target/idl/solana_twitter.json app/src/anchor/idl/solana_twitter.json"
copy-types = "mkdir -p app/src/anchor/types && cp target/types/solana_twitter.ts app/src/anchor/types/solana_twitter.ts"
