[programs.localnet]
solana_twitter = "DEVemLxXHPz1tbnBbTVXtvNBHupP2RCBw1jTFN8Uz3FD"

[programs.devnet]
solana_twitter = "DEVemLxXHPz1tbnBbTVXtvNBHupP2RCBw1jTFN8Uz3FD"

[programs.mainnet]
solana_twitter = "DEVemLxXHPz1tbnBbTVXtvNBHupP2RCBw1jTFN8Uz3FD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
