name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - feature/github-pages
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Build Vue
        run: |
          ls ${{ github.workspace }}
          cd ./app
          yarn --frozen-lockfile
          rm -rf ./dist
          export NODE_ENV=production
          yarn build:devnet
          cd ./dist
          cp ./index.html ./404.html
      - name: Trigger deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
      - run: echo "🍏 This job's status is ${{ job.status }}."
